config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'customers#index'

  resources :customers do
    resources :orders, only: :create
  end

  resources :persons, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one :order
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :init_messages

  private

  def init_messages
    puts flash[:notice].inspect
    flash[:notice] = [] if flash[:notice].nil?
    flash[:error] = [] if flash[:error].nil?
    puts flash[:notice].inspect
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @total = Customer.count
    @customers = Customer.all

    last_customer = Customer.last
    @customer = last_customer.order.present? ? Customer.new : last_customer
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    customer = Customer.find(params[:customer_id]) rescue nil;
    order = Order.new(token: params[:stripeToken], customer: customer)

    respond_to do |format|
      if order.save
        # flash[:notice].push 'Customer created successfully'
      else
        # flash[:error].push "Error: #{@customer.errors.full_messages.join('. ')}"
      end

      format.html { redirect_to customers_path }
    end
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def create
    @customer =  Customer.new(name: params[:stripeEmail])

    respond_to do |format|
      if @customer.save
        # flash[:notice].push 'Customer created successfully'
      else
        # flash[:error].push "Error: #{@customer.errors.full_messages.join('. ')}"
      end

      format.html { redirect_to root_path }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/common/__messages.html.erb
<h2>Messages:</h2>

<% if flash[:notice].present? %>
  <% flash[:notice].each do |msg| %>
    <p><%= msg %></p>
  <% end %>
<% end %>

<% if flash[:error].present? %>
  <% flash[:error].each do |msg| %>
    <p><%= msg %></p>
  <% end %>
<% end %>

app/views/customers/index.html.erb
<h1>Customers:</h1>

<%= render 'common/_messages'%>

<%= form_for (@customer.new_record?) ? @customer : Order.new, url: @customer.new_record? ? persons_path : customer_orders_path(customer_id: @customer.id) do |f| %>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="<%="Persona"%>"
    data-amount="<%= 1000 %>"

    data-allow-remember-me="false"
    data-name="<%= "Persona" %>"
    data-locale="auto">
  </script>
<% end %>

<hr/>

<% if @customers.present? %>
<ul>
  <% @customers.each do |customer| %>
    <li>
      <%= customer.inspect %>
      <br/> <%= customer.order.inspect %>
      <br/><br/>
    </li>
  <% end %>
</ul>
<% end %>

<div>Total Customers: <%= @total %></div>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'common/_messages'%>

<%= form_for @customer do |f| %>
  <%= f.label :name %><br/>
  <%= f.text_field :name %>
  <%= f.submit "Create" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails52</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>